# Generated by Django 4.2.11 on 2024-07-06 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('comedy', 'Comedy'), ('romance', 'Romance'), ('fantasy', 'Fantasy')], max_length=100),
        ),
    ]
